/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exemplos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Exemplos */
        get: operations["exemplos_api_v1_exemplos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/perguntas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Perguntas */
        post: operations["perguntas_api_v1_perguntas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DadosResposta */
        DadosResposta: {
            /** Colunas */
            colunas: string[];
            /** Linhas */
            linhas: unknown[][];
            /** Truncado */
            truncado: boolean;
        };
        /** ErroAPI */
        ErroAPI: {
            /** Erro */
            erro: string;
        };
        /** ListaExemplos */
        ListaExemplos: {
            /** Perguntas */
            perguntas: string[];
        };
        /** Metadados */
        Metadados: {
            /** Modelo */
            modelo: string;
            /** Requisicoes */
            requisicoes: number;
            /** Tempo Ms */
            tempo_ms: number;
            /** Cache */
            cache: boolean;
        };
        /** PedidoPergunta */
        PedidoPergunta: {
            /**
             * Pergunta
             * @example Top 10 filmes com maior receita em R$
             */
            pergunta: string;
            /** Conversa Id */
            conversa_id?: string | null;
        };
        /** RespostaServico */
        RespostaServico: {
            /** Conversa Id */
            conversa_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "fora_do_escopo" | "erro";
            /** Resposta */
            resposta: string;
            /** Sql */
            sql?: string | null;
            /**
             * Explicacao
             * @default
             */
            explicacao: string;
            dados?: components["schemas"]["DadosResposta"] | null;
            visualizacao?: components["schemas"]["Visualizacao"];
            metadados: components["schemas"]["Metadados"];
        };
        /** Saude */
        Saude: {
            /** Banco */
            banco: boolean;
            /** Provedor */
            provedor: boolean;
        };
        /**
         * Visualizacao
         * @description Sugestão de gráfico para um frontend futuro. O modelo preenche depois de ver as linhas.
         */
        Visualizacao: {
            /**
             * Tipo
             * @default tabela
             * @enum {string}
             */
            tipo: "tabela" | "barra" | "linha" | "nenhum";
            /** Eixos */
            eixos?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Saude"];
                };
            };
        };
    };
    exemplos_api_v1_exemplos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListaExemplos"];
                };
            };
        };
    };
    perguntas_api_v1_perguntas_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PedidoPergunta"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "conversa_id": "sessao-1",
                     *       "status": "ok",
                     *       "resposta": "Avatar lidera a receita.",
                     *       "sql": "SELECT titulo, receita_brl FROM dim_movies LIMIT 10",
                     *       "explicacao": "Ordenei por receita em reais.",
                     *       "dados": {
                     *         "colunas": [
                     *           "titulo",
                     *           "receita_brl"
                     *         ],
                     *         "linhas": [
                     *           [
                     *             "Avatar",
                     *             1
                     *           ]
                     *         ],
                     *         "truncado": false
                     *       },
                     *       "visualizacao": {
                     *         "tipo": "barra",
                     *         "eixos": [
                     *           "titulo",
                     *           "receita_brl"
                     *         ]
                     *       },
                     *       "metadados": {
                     *         "modelo": "gemini-3.5-flash-lite",
                     *         "requisicoes": 2,
                     *         "tempo_ms": 1200,
                     *         "cache": false
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["RespostaServico"];
                };
            };
            /** @description Pergunta vazia. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroAPI"];
                };
            };
            /** @description Nenhum provedor disponível. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroAPI"];
                };
            };
            /** @description A consulta SQL excedeu o tempo. */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroAPI"];
                };
            };
        };
    };
}
